[package]
name = "rmdup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cab = "0.5.0"
clap = "2"
crc32fast = "1.4.0"
fs_extra = "1.3.0"
tempfile = "3.10.1"
zip = "0.6.6"
