[package]
name = "rmdup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cab = "0.5.0"
clap = "2"
zip = "0.6.6"
